// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :execlastid
INSERT INTO agent_sessions(thread_id, trigger_message_id, agent_name, status, reply_mode, command, cwd)
VALUES(?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ThreadID         int64
	TriggerMessageID int64
	AgentName        string
	Status           string
	ReplyMode        string
	Command          string
	Cwd              *string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSession,
		arg.ThreadID,
		arg.TriggerMessageID,
		arg.AgentName,
		arg.Status,
		arg.ReplyMode,
		arg.Command,
		arg.Cwd,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const finishSession = `-- name: FinishSession :execrows
UPDATE agent_sessions SET status = ?, exit_code = ?, error = ?, finished_at = ? WHERE id = ?
`

type FinishSessionParams struct {
	Status     string
	ExitCode   *int64
	Error      *string
	FinishedAt *string
	ID         int64
}

func (q *Queries) FinishSession(ctx context.Context, arg FinishSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishSession,
		arg.Status,
		arg.ExitCode,
		arg.Error,
		arg.FinishedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSession = `-- name: GetSession :one
SELECT id, thread_id, trigger_message_id, agent_name, status, reply_mode, command,
       cwd, exit_code, error, reply_message_id, started_at, finished_at, created_at
FROM agent_sessions
WHERE id = ?
`

type GetSessionParams struct {
	ID int64
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (AgentSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.ID)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.TriggerMessageID,
		&i.AgentName,
		&i.Status,
		&i.ReplyMode,
		&i.Command,
		&i.Cwd,
		&i.ExitCode,
		&i.Error,
		&i.ReplyMessageID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getThreadContext = `-- name: GetThreadContext :one
SELECT t.id AS thread_id, t.title AS thread_title, c.id AS channel_id, c.name AS channel_name, c.repo_abs_path
FROM threads t
JOIN channels c ON c.id = t.channel_id
WHERE t.id = ?
`

type GetThreadContextParams struct {
	ID int64
}

type GetThreadContextRow struct {
	ThreadID    int64
	ThreadTitle string
	ChannelID   int64
	ChannelName string
	RepoAbsPath *string
}

func (q *Queries) GetThreadContext(ctx context.Context, arg GetThreadContextParams) (GetThreadContextRow, error) {
	row := q.db.QueryRowContext(ctx, getThreadContext, arg.ID)
	var i GetThreadContextRow
	err := row.Scan(
		&i.ThreadID,
		&i.ThreadTitle,
		&i.ChannelID,
		&i.ChannelName,
		&i.RepoAbsPath,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, thread_id, trigger_message_id, agent_name, status, reply_mode, command,
       cwd, exit_code, error, reply_message_id, started_at, finished_at, created_at
FROM agent_sessions
WHERE thread_id = ?
ORDER BY id ASC
`

type ListSessionsParams struct {
	ThreadID int64
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]AgentSession, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentSession
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.TriggerMessageID,
			&i.AgentName,
			&i.Status,
			&i.ReplyMode,
			&i.Command,
			&i.Cwd,
			&i.ExitCode,
			&i.Error,
			&i.ReplyMessageID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionRunning = `-- name: MarkSessionRunning :execrows
UPDATE agent_sessions SET status = ?, started_at = ? WHERE id = ? AND status = ?
`

type MarkSessionRunningParams struct {
	Status    string
	StartedAt *string
	ID        int64
	Status_2  string
}

func (q *Queries) MarkSessionRunning(ctx context.Context, arg MarkSessionRunningParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markSessionRunning,
		arg.Status,
		arg.StartedAt,
		arg.ID,
		arg.Status_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reconcileSessions = `-- name: ReconcileSessions :execrows
UPDATE agent_sessions
SET status = ?, finished_at = ?, error = 'daemon restarted while ' || status
WHERE status IN (?, ?)
`

type ReconcileSessionsParams struct {
	Status     string
	FinishedAt *string
	Status_2   string
	Status_3   string
}

func (q *Queries) ReconcileSessions(ctx context.Context, arg ReconcileSessionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reconcileSessions,
		arg.Status,
		arg.FinishedAt,
		arg.Status_2,
		arg.Status_3,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSessionReply = `-- name: SetSessionReply :execrows
UPDATE agent_sessions SET reply_message_id = ? WHERE id = ?
`

type SetSessionReplyParams struct {
	ReplyMessageID *int64
	ID             int64
}

func (q *Queries) SetSessionReply(ctx context.Context, arg SetSessionReplyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSessionReply, arg.ReplyMessageID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
