// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_session_events.sql

package db

import (
	"context"
)

const getSessionEventMaxSeq = `-- name: GetSessionEventMaxSeq :one
SELECT MAX(seq) FROM agent_session_events WHERE session_id = ?
`

type GetSessionEventMaxSeqParams struct {
	SessionID int64
}

func (q *Queries) GetSessionEventMaxSeq(ctx context.Context, arg GetSessionEventMaxSeqParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getSessionEventMaxSeq, arg.SessionID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const insertSessionEvent = `-- name: InsertSessionEvent :execlastid
INSERT INTO agent_session_events(session_id, seq, type, content)
VALUES(?, ?, ?, ?)
`

type InsertSessionEventParams struct {
	SessionID int64
	Seq       int64
	Type      string
	Content   string
}

func (q *Queries) InsertSessionEvent(ctx context.Context, arg InsertSessionEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertSessionEvent,
		arg.SessionID,
		arg.Seq,
		arg.Type,
		arg.Content,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listSessionEvents = `-- name: ListSessionEvents :many
SELECT id, session_id, seq, type, content, COALESCE(created_at, '') AS created_at
FROM agent_session_events
WHERE session_id = ?
ORDER BY seq ASC
`

type ListSessionEventsParams struct {
	SessionID int64
}

func (q *Queries) ListSessionEvents(ctx context.Context, arg ListSessionEventsParams) ([]AgentSessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSessionEvents, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentSessionEvent
	for rows.Next() {
		var i AgentSessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Seq,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
