// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"
)

const createChannel = `-- name: CreateChannel :execlastid
INSERT INTO channels(name, repo_abs_path, repo_remote, repo_head_sha, repo_head_branch, is_orphaned)
VALUES(?, ?, ?, ?, ?, ?)
`

type CreateChannelParams struct {
	Name           string
	RepoAbsPath    *string
	RepoRemote     *string
	RepoHeadSHA    *string
	RepoHeadBranch *string
	IsOrphaned     int64
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createChannel,
		arg.Name,
		arg.RepoAbsPath,
		arg.RepoRemote,
		arg.RepoHeadSHA,
		arg.RepoHeadBranch,
		arg.IsOrphaned,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listChannelsAll = `-- name: ListChannelsAll :many
SELECT id, name,
       COALESCE(repo_abs_path, '') AS repo_abs_path,
       COALESCE(repo_remote, '') AS repo_remote,
       COALESCE(repo_head_sha, '') AS repo_head_sha,
       COALESCE(repo_head_branch, '') AS repo_head_branch,
       is_orphaned,
       COALESCE(created_at, '') AS created_at
FROM channels
ORDER BY id
`

type ListChannelsAllRow struct {
	ID             int64
	Name           string
	RepoAbsPath    string
	RepoRemote     string
	RepoHeadSHA    string
	RepoHeadBranch string
	IsOrphaned     int64
	CreatedAt      string
}

func (q *Queries) ListChannelsAll(ctx context.Context) ([]ListChannelsAllRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsAllRow
	for rows.Next() {
		var i ListChannelsAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoAbsPath,
			&i.RepoRemote,
			&i.RepoHeadSHA,
			&i.RepoHeadBranch,
			&i.IsOrphaned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsByRepo = `-- name: ListChannelsByRepo :many
SELECT id, name,
       COALESCE(repo_abs_path, '') AS repo_abs_path,
       COALESCE(repo_remote, '') AS repo_remote,
       COALESCE(repo_head_sha, '') AS repo_head_sha,
       COALESCE(repo_head_branch, '') AS repo_head_branch,
       is_orphaned,
       COALESCE(created_at, '') AS created_at
FROM channels
WHERE repo_abs_path = ?
ORDER BY id
`

type ListChannelsByRepoParams struct {
	RepoAbsPath *string
}

type ListChannelsByRepoRow struct {
	ID             int64
	Name           string
	RepoAbsPath    string
	RepoRemote     string
	RepoHeadSHA    string
	RepoHeadBranch string
	IsOrphaned     int64
	CreatedAt      string
}

func (q *Queries) ListChannelsByRepo(ctx context.Context, arg ListChannelsByRepoParams) ([]ListChannelsByRepoRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsByRepo, arg.RepoAbsPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsByRepoRow
	for rows.Next() {
		var i ListChannelsByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoAbsPath,
			&i.RepoRemote,
			&i.RepoHeadSHA,
			&i.RepoHeadBranch,
			&i.IsOrphaned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsByRepoNonOrphaned = `-- name: ListChannelsByRepoNonOrphaned :many
SELECT id, name,
       COALESCE(repo_abs_path, '') AS repo_abs_path,
       COALESCE(repo_remote, '') AS repo_remote,
       COALESCE(repo_head_sha, '') AS repo_head_sha,
       COALESCE(repo_head_branch, '') AS repo_head_branch,
       is_orphaned,
       COALESCE(created_at, '') AS created_at
FROM channels
WHERE repo_abs_path = ? AND is_orphaned = 0
ORDER BY id
`

type ListChannelsByRepoNonOrphanedParams struct {
	RepoAbsPath *string
}

type ListChannelsByRepoNonOrphanedRow struct {
	ID             int64
	Name           string
	RepoAbsPath    string
	RepoRemote     string
	RepoHeadSHA    string
	RepoHeadBranch string
	IsOrphaned     int64
	CreatedAt      string
}

func (q *Queries) ListChannelsByRepoNonOrphaned(ctx context.Context, arg ListChannelsByRepoNonOrphanedParams) ([]ListChannelsByRepoNonOrphanedRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsByRepoNonOrphaned, arg.RepoAbsPath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsByRepoNonOrphanedRow
	for rows.Next() {
		var i ListChannelsByRepoNonOrphanedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoAbsPath,
			&i.RepoRemote,
			&i.RepoHeadSHA,
			&i.RepoHeadBranch,
			&i.IsOrphaned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsNonOrphaned = `-- name: ListChannelsNonOrphaned :many
SELECT id, name,
       COALESCE(repo_abs_path, '') AS repo_abs_path,
       COALESCE(repo_remote, '') AS repo_remote,
       COALESCE(repo_head_sha, '') AS repo_head_sha,
       COALESCE(repo_head_branch, '') AS repo_head_branch,
       is_orphaned,
       COALESCE(created_at, '') AS created_at
FROM channels
WHERE is_orphaned = 0
ORDER BY id
`

type ListChannelsNonOrphanedRow struct {
	ID             int64
	Name           string
	RepoAbsPath    string
	RepoRemote     string
	RepoHeadSHA    string
	RepoHeadBranch string
	IsOrphaned     int64
	CreatedAt      string
}

func (q *Queries) ListChannelsNonOrphaned(ctx context.Context) ([]ListChannelsNonOrphanedRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsNonOrphaned)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsNonOrphanedRow
	for rows.Next() {
		var i ListChannelsNonOrphanedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoAbsPath,
			&i.RepoRemote,
			&i.RepoHeadSHA,
			&i.RepoHeadBranch,
			&i.IsOrphaned,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
