// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const countAgentMessagesAfter = `-- name: CountAgentMessagesAfter :one
SELECT COUNT(*) FROM messages
WHERE thread_id = ? AND name = ? AND author_type = 'agent' AND seq > ?
`

type CountAgentMessagesAfterParams struct {
	ThreadID int64
	Name     string
	Seq      int64
}

func (q *Queries) CountAgentMessagesAfter(ctx context.Context, arg CountAgentMessagesAfterParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentMessagesAfter, arg.ThreadID, arg.Name, arg.Seq)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLastMessageSeq = `-- name: GetLastMessageSeq :one
SELECT seq FROM messages WHERE thread_id = ? ORDER BY seq DESC LIMIT 1
`

type GetLastMessageSeqParams struct {
	ThreadID int64
}

func (q *Queries) GetLastMessageSeq(ctx context.Context, arg GetLastMessageSeqParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLastMessageSeq, arg.ThreadID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const getMessageByIDWithParent = `-- name: GetMessageByIDWithParent :one
SELECT m.id, m.thread_id, m.seq, m.parent_id, p.seq AS parent_seq, m.name, m.author_type, m.role, m.content,
       COALESCE(m.created_at, '') AS created_at
FROM messages m
LEFT JOIN messages p ON p.id = m.parent_id
WHERE m.id = ?
`

type GetMessageByIDWithParentParams struct {
	ID int64
}

type GetMessageByIDWithParentRow struct {
	ID         int64
	ThreadID   int64
	Seq        int64
	ParentID   sql.NullInt64
	ParentSeq  *int64
	Name       string
	AuthorType string
	Role       string
	Content    string
	CreatedAt  string
}

func (q *Queries) GetMessageByIDWithParent(ctx context.Context, arg GetMessageByIDWithParentParams) (GetMessageByIDWithParentRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageByIDWithParent, arg.ID)
	var i GetMessageByIDWithParentRow
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Seq,
		&i.ParentID,
		&i.ParentSeq,
		&i.Name,
		&i.AuthorType,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageIDByThreadSeq = `-- name: GetMessageIDByThreadSeq :one
SELECT id FROM messages WHERE thread_id = ? AND seq = ?
`

type GetMessageIDByThreadSeqParams struct {
	ThreadID int64
	Seq      int64
}

func (q *Queries) GetMessageIDByThreadSeq(ctx context.Context, arg GetMessageIDByThreadSeqParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMessageIDByThreadSeq, arg.ThreadID, arg.Seq)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMessageThreadIDByID = `-- name: GetMessageThreadIDByID :one
SELECT thread_id FROM messages WHERE id = ?
`

type GetMessageThreadIDByIDParams struct {
	ID int64
}

func (q *Queries) GetMessageThreadIDByID(ctx context.Context, arg GetMessageThreadIDByIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMessageThreadIDByID, arg.ID)
	var thread_id int64
	err := row.Scan(&thread_id)
	return thread_id, err
}

const insertMessage = `-- name: InsertMessage :execlastid
INSERT INTO messages(thread_id, seq, parent_id, name, author_type, role, content, created_at)
VALUES(?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	ThreadID   int64
	Seq        int64
	ParentID   sql.NullInt64
	Name       string
	AuthorType string
	Role       string
	Content    string
	CreatedAt  string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertMessage,
		arg.ThreadID,
		arg.Seq,
		arg.ParentID,
		arg.Name,
		arg.AuthorType,
		arg.Role,
		arg.Content,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertMessageDefaultCreatedAt = `-- name: InsertMessageDefaultCreatedAt :execlastid
INSERT INTO messages(thread_id, seq, parent_id, name, author_type, role, content)
VALUES(?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageDefaultCreatedAtParams struct {
	ThreadID   int64
	Seq        int64
	ParentID   sql.NullInt64
	Name       string
	AuthorType string
	Role       string
	Content    string
}

func (q *Queries) InsertMessageDefaultCreatedAt(ctx context.Context, arg InsertMessageDefaultCreatedAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertMessageDefaultCreatedAt,
		arg.ThreadID,
		arg.Seq,
		arg.ParentID,
		arg.Name,
		arg.AuthorType,
		arg.Role,
		arg.Content,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listInbox = `-- name: ListInbox :many
SELECT m.id, m.thread_id, m.seq, m.parent_id, m.name, m.author_type, m.role, m.content,
       COALESCE(m.created_at, '') AS created_at,
       c.name AS channel_name, c.id AS channel_id, t.title AS thread_title
FROM messages m
JOIN threads t ON t.id = m.thread_id
JOIN channels c ON c.id = t.channel_id
ORDER BY m.created_at DESC, m.id DESC
LIMIT ?
`

type ListInboxParams struct {
	Limit int64
}

type ListInboxRow struct {
	ID          int64
	ThreadID    int64
	Seq         int64
	ParentID    sql.NullInt64
	Name        string
	AuthorType  string
	Role        string
	Content     string
	CreatedAt   string
	ChannelName string
	ChannelID   int64
	ThreadTitle string
}

func (q *Queries) ListInbox(ctx context.Context, arg ListInboxParams) ([]ListInboxRow, error) {
	rows, err := q.db.QueryContext(ctx, listInbox, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboxRow
	for rows.Next() {
		var i ListInboxRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Seq,
			&i.ParentID,
			&i.Name,
			&i.AuthorType,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.ChannelName,
			&i.ChannelID,
			&i.ThreadTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT m.id, m.thread_id, m.seq, m.parent_id, p.seq AS parent_seq, m.name, m.author_type, m.role, m.content,
       COALESCE(m.created_at, '') AS created_at
FROM messages m
LEFT JOIN messages p ON p.id = m.parent_id
WHERE m.thread_id = ?
ORDER BY m.seq ASC
`

type ListMessagesParams struct {
	ThreadID int64
}

type ListMessagesRow struct {
	ID         int64
	ThreadID   int64
	Seq        int64
	ParentID   sql.NullInt64
	ParentSeq  *int64
	Name       string
	AuthorType string
	Role       string
	Content    string
	CreatedAt  string
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Seq,
			&i.ParentID,
			&i.ParentSeq,
			&i.Name,
			&i.AuthorType,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesAfter = `-- name: ListMessagesAfter :many
SELECT m.id, m.thread_id, m.seq, m.parent_id, p.seq AS parent_seq, m.name, m.author_type, m.role, m.content,
       COALESCE(m.created_at, '') AS created_at
FROM messages m
LEFT JOIN messages p ON p.id = m.parent_id
WHERE m.thread_id = ? AND m.seq > ?
ORDER BY m.seq ASC
`

type ListMessagesAfterParams struct {
	ThreadID int64
	Seq      int64
}

type ListMessagesAfterRow struct {
	ID         int64
	ThreadID   int64
	Seq        int64
	ParentID   sql.NullInt64
	ParentSeq  *int64
	Name       string
	AuthorType string
	Role       string
	Content    string
	CreatedAt  string
}

func (q *Queries) ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]ListMessagesAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesAfter, arg.ThreadID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesAfterRow
	for rows.Next() {
		var i ListMessagesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Seq,
			&i.ParentID,
			&i.ParentSeq,
			&i.Name,
			&i.AuthorType,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesLastN = `-- name: ListMessagesLastN :many
SELECT id, thread_id, seq, parent_id, parent_seq, name, author_type, role, content, created_at FROM (
  SELECT id, thread_id, seq, parent_id, parent_seq, name, author_type, role, content, created_at FROM (
    SELECT m.id, m.thread_id, m.seq, m.parent_id, p.seq AS parent_seq, m.name, m.author_type, m.role, m.content,
           COALESCE(m.created_at, '') AS created_at
    FROM messages m
    LEFT JOIN messages p ON p.id = m.parent_id
    WHERE m.thread_id = ?
    ORDER BY m.seq ASC
  ) ORDER BY seq DESC LIMIT ?
) ORDER BY seq ASC
`

type ListMessagesLastNParams struct {
	ThreadID int64
	Limit    int64
}

type ListMessagesLastNRow struct {
	ID         int64
	ThreadID   int64
	Seq        int64
	ParentID   sql.NullInt64
	ParentSeq  *int64
	Name       string
	AuthorType string
	Role       string
	Content    string
	CreatedAt  string
}

func (q *Queries) ListMessagesLastN(ctx context.Context, arg ListMessagesLastNParams) ([]ListMessagesLastNRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesLastN, arg.ThreadID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesLastNRow
	for rows.Next() {
		var i ListMessagesLastNRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Seq,
			&i.ParentID,
			&i.ParentSeq,
			&i.Name,
			&i.AuthorType,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
