// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type AgentSession struct {
	ID               int64
	ThreadID         int64
	TriggerMessageID int64
	AgentName        string
	Status           string
	ReplyMode        string
	Command          string
	Cwd              *string
	ExitCode         *int64
	Error            *string
	ReplyMessageID   *int64
	StartedAt        *string
	FinishedAt       *string
	CreatedAt        string
}

type AgentSessionEvent struct {
	ID        int64
	SessionID int64
	Seq       int64
	Type      string
	Content   string
	CreatedAt string
}

type Channel struct {
	ID             int64
	Name           string
	RepoAbsPath    *string
	RepoRemote     *string
	RepoHeadSHA    *string
	RepoHeadBranch *string
	IsOrphaned     int64
	CreatedAt      string
}

type Message struct {
	ID         int64
	ThreadID   int64
	Seq        int64
	ParentID   sql.NullInt64
	Name       string
	AuthorType string
	Role       string
	Content    string
	CreatedAt  string
}

type Reaction struct {
	ID         int64
	MessageID  int64
	Emoji      string
	Name       string
	AuthorType string
	CreatedAt  string
}

type Thread struct {
	ID        int64
	ChannelID int64
	Title     string
	CreatedAt string
}
