// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountAgentMessagesAfter(ctx context.Context, arg CountAgentMessagesAfterParams) (int64, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error)
	CreateThread(ctx context.Context, arg CreateThreadParams) (int64, error)
	FinishSession(ctx context.Context, arg FinishSessionParams) (int64, error)
	GetLastMessageSeq(ctx context.Context, arg GetLastMessageSeqParams) (int64, error)
	GetLastSessionEventSeq(ctx context.Context, arg GetLastSessionEventSeqParams) (int64, error)
	GetMessageByIDWithParent(ctx context.Context, arg GetMessageByIDWithParentParams) (GetMessageByIDWithParentRow, error)
	GetMessageIDByThreadSeq(ctx context.Context, arg GetMessageIDByThreadSeqParams) (int64, error)
	GetMessageThreadIDByID(ctx context.Context, arg GetMessageThreadIDByIDParams) (int64, error)
	GetSession(ctx context.Context, arg GetSessionParams) (AgentSession, error)
	GetThreadContext(ctx context.Context, arg GetThreadContextParams) (GetThreadContextRow, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error)
	InsertMessageDefaultCreatedAt(ctx context.Context, arg InsertMessageDefaultCreatedAtParams) (int64, error)
	InsertReaction(ctx context.Context, arg InsertReactionParams) (int64, error)
	InsertReactionDefaultCreatedAt(ctx context.Context, arg InsertReactionDefaultCreatedAtParams) (int64, error)
	InsertSessionEvent(ctx context.Context, arg InsertSessionEventParams) (int64, error)
	ListChannelRows(ctx context.Context, arg ListChannelRowsParams) ([]ListChannelRowsRow, error)
	ListChannelsAll(ctx context.Context) ([]ListChannelsAllRow, error)
	ListChannelsByRepo(ctx context.Context, arg ListChannelsByRepoParams) ([]ListChannelsByRepoRow, error)
	ListChannelsByRepoNonOrphaned(ctx context.Context, arg ListChannelsByRepoNonOrphanedParams) ([]ListChannelsByRepoNonOrphanedRow, error)
	ListChannelsNonOrphaned(ctx context.Context) ([]ListChannelsNonOrphanedRow, error)
	ListInbox(ctx context.Context, arg ListInboxParams) ([]ListInboxRow, error)
	ListMessageRows(ctx context.Context, arg ListMessageRowsParams) ([]ListMessageRowsRow, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error)
	ListMessagesAfter(ctx context.Context, arg ListMessagesAfterParams) ([]ListMessagesAfterRow, error)
	ListMessagesLastN(ctx context.Context, arg ListMessagesLastNParams) ([]ListMessagesLastNRow, error)
	ListReactions(ctx context.Context, arg ListReactionsParams) ([]ListReactionsRow, error)
	ListSessionEvents(ctx context.Context, arg ListSessionEventsParams) ([]AgentSessionEvent, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]AgentSession, error)
	ListThreadRows(ctx context.Context, arg ListThreadRowsParams) ([]ListThreadRowsRow, error)
	ListThreads(ctx context.Context, arg ListThreadsParams) ([]Thread, error)
	MarkSessionRunning(ctx context.Context, arg MarkSessionRunningParams) (int64, error)
	ReconcileSessions(ctx context.Context, arg ReconcileSessionsParams) (int64, error)
	SetSessionReply(ctx context.Context, arg SetSessionReplyParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
