// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reactions.sql

package db

import (
	"context"
)

const insertReaction = `-- name: InsertReaction :execlastid
INSERT INTO reactions(message_id, emoji, name, author_type, created_at)
VALUES(?, ?, ?, ?, ?)
`

type InsertReactionParams struct {
	MessageID  int64
	Emoji      string
	Name       string
	AuthorType string
	CreatedAt  string
}

func (q *Queries) InsertReaction(ctx context.Context, arg InsertReactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertReaction,
		arg.MessageID,
		arg.Emoji,
		arg.Name,
		arg.AuthorType,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertReactionDefaultCreatedAt = `-- name: InsertReactionDefaultCreatedAt :execlastid
INSERT INTO reactions(message_id, emoji, name, author_type)
VALUES(?, ?, ?, ?)
`

type InsertReactionDefaultCreatedAtParams struct {
	MessageID  int64
	Emoji      string
	Name       string
	AuthorType string
}

func (q *Queries) InsertReactionDefaultCreatedAt(ctx context.Context, arg InsertReactionDefaultCreatedAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertReactionDefaultCreatedAt,
		arg.MessageID,
		arg.Emoji,
		arg.Name,
		arg.AuthorType,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listReactions = `-- name: ListReactions :many
SELECT r.id, r.message_id, m.seq AS message_seq, r.emoji, r.name, r.author_type,
       COALESCE(r.created_at, '') AS created_at
FROM reactions r
JOIN messages m ON m.id = r.message_id
WHERE m.thread_id = ?
ORDER BY m.seq ASC, r.created_at ASC, r.id ASC
`

type ListReactionsParams struct {
	ThreadID int64
}

type ListReactionsRow struct {
	ID         int64
	MessageID  int64
	MessageSeq int64
	Emoji      string
	Name       string
	AuthorType string
	CreatedAt  string
}

func (q *Queries) ListReactions(ctx context.Context, arg ListReactionsParams) ([]ListReactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReactions, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReactionsRow
	for rows.Next() {
		var i ListReactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.MessageSeq,
			&i.Emoji,
			&i.Name,
			&i.AuthorType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
