// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rows.sql

package db

import (
	"context"
)

const listChannelRows = `-- name: ListChannelRows :many
SELECT c.id AS id,
       0 AS thread_id,
       COALESCE((SELECT m.created_at FROM messages m JOIN threads t2 ON t2.id = m.thread_id
                 WHERE t2.channel_id = c.id
                 ORDER BY m.created_at DESC, m.id DESC LIMIT 1), c.created_at) AS created_at,
       c.name AS channel,
       '' AS thread,
       CAST(COALESCE((SELECT m.name FROM messages m JOIN threads t2 ON t2.id = m.thread_id
                      WHERE t2.channel_id = c.id
                      ORDER BY m.created_at DESC, m.id DESC LIMIT 1), '') AS TEXT) AS name,
       CAST(COALESCE((SELECT m.content FROM messages m JOIN threads t2 ON t2.id = m.thread_id
                      WHERE t2.channel_id = c.id
                      ORDER BY m.created_at DESC, m.id DESC LIMIT 1), '') AS TEXT) AS content,
       (SELECT COUNT(*) FROM messages m JOIN threads t2 ON t2.id = m.thread_id
        WHERE t2.channel_id = c.id) AS msg_count
FROM channels c
ORDER BY created_at DESC, c.id DESC
LIMIT ?
`

type ListChannelRowsParams struct {
	Limit int64
}

type ListChannelRowsRow struct {
	ID        int64
	ThreadID  int64
	CreatedAt string
	Channel   string
	Thread    string
	Name      string
	Content   string
	MsgCount  int64
}

func (q *Queries) ListChannelRows(ctx context.Context, arg ListChannelRowsParams) ([]ListChannelRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelRows, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelRowsRow
	for rows.Next() {
		var i ListChannelRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.CreatedAt,
			&i.Channel,
			&i.Thread,
			&i.Name,
			&i.Content,
			&i.MsgCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageRows = `-- name: ListMessageRows :many
SELECT m.id AS id,
       m.thread_id AS thread_id,
       COALESCE(m.created_at, '') AS created_at,
       c.name AS channel,
       t.title AS thread,
       m.name AS name,
       m.content AS content
FROM messages m
JOIN threads t ON t.id = m.thread_id
JOIN channels c ON c.id = t.channel_id
ORDER BY m.created_at DESC, m.id DESC
LIMIT ?
`

type ListMessageRowsParams struct {
	Limit int64
}

type ListMessageRowsRow struct {
	ID        int64
	ThreadID  int64
	CreatedAt string
	Channel   string
	Thread    string
	Name      string
	Content   string
}

func (q *Queries) ListMessageRows(ctx context.Context, arg ListMessageRowsParams) ([]ListMessageRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessageRows, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessageRowsRow
	for rows.Next() {
		var i ListMessageRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.CreatedAt,
			&i.Channel,
			&i.Thread,
			&i.Name,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadRows = `-- name: ListThreadRows :many
SELECT t.id AS id,
       t.id AS thread_id,
       COALESCE((SELECT m.created_at FROM messages m
                 WHERE m.thread_id = t.id
                 ORDER BY m.created_at DESC, m.id DESC LIMIT 1), t.created_at) AS created_at,
       c.name AS channel,
       t.title AS thread,
       CAST(COALESCE((SELECT m.name FROM messages m
                      WHERE m.thread_id = t.id
                      ORDER BY m.created_at DESC, m.id DESC LIMIT 1), '') AS TEXT) AS name,
       CAST(COALESCE((SELECT m.content FROM messages m
                      WHERE m.thread_id = t.id
                      ORDER BY m.seq ASC LIMIT 1), '') AS TEXT) AS content,
       (SELECT COUNT(*) FROM messages m WHERE m.thread_id = t.id) AS msg_count
FROM threads t
JOIN channels c ON c.id = t.channel_id
ORDER BY created_at DESC, t.id DESC
LIMIT ?
`

type ListThreadRowsParams struct {
	Limit int64
}

type ListThreadRowsRow struct {
	ID        int64
	ThreadID  int64
	CreatedAt string
	Channel   string
	Thread    string
	Name      string
	Content   string
	MsgCount  int64
}

func (q *Queries) ListThreadRows(ctx context.Context, arg ListThreadRowsParams) ([]ListThreadRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listThreadRows, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadRowsRow
	for rows.Next() {
		var i ListThreadRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.CreatedAt,
			&i.Channel,
			&i.Thread,
			&i.Name,
			&i.Content,
			&i.MsgCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
