// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threads.sql

package db

import (
	"context"
)

const countThreadsByID = `-- name: CountThreadsByID :one
SELECT COUNT(*) FROM threads WHERE id = ?
`

type CountThreadsByIDParams struct {
	ID int64
}

func (q *Queries) CountThreadsByID(ctx context.Context, arg CountThreadsByIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countThreadsByID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createThread = `-- name: CreateThread :execlastid
INSERT INTO threads(channel_id, title) VALUES(?, ?)
`

type CreateThreadParams struct {
	ChannelID int64
	Title     string
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createThread, arg.ChannelID, arg.Title)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listThreads = `-- name: ListThreads :many
SELECT id, channel_id, title, COALESCE(created_at, '') AS created_at
FROM threads
WHERE channel_id = ?
ORDER BY id
`

type ListThreadsParams struct {
	ChannelID int64
}

func (q *Queries) ListThreads(ctx context.Context, arg ListThreadsParams) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, listThreads, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
